version: "3.7"

services:
  backend:
    container_name: platform_backend
    build: 
      context: .
      dockerfile: Dockerfile.fastapi
    tty: true
    volumes: 
      - "./backend:/var/www/"
  frontend:
    container_name: platform_frontend
    build: 
      context: .
      dockerfile: Dockerfile.spa
    tty: true
    volumes: 
      - "./frontend/app/:/var/www/"
  nginx_proxy:
    container_name: platform_proxy
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    depends_on:
      - backend
      - frontend
    # links:
    #   - backend
    #   - frontend
    networks:
      - platform_net
    ports:
      - 80:80
      - 443:443
    tty: true
    volumes: 
      - "./nginx:/etc/www/"
  redis:
    container_name: platform_redis
    image: redis:latest
    command: redis redis-server --save 60 1 --loglevel warning
    tty: true

networks:
  platform_net:
   
